PRAGMA foreign_keys = ON;

ALTER TABLE currency ADD COLUMN name TEXT;
ALTER TABLE currency ADD COLUMN country_name TEXT;
ALTER TABLE currency ADD COLUMN country_code TEXT;

UPDATE currency SET name = 'Peso Mexicano ($)', country_name = 'México', country_code = 'MX' WHERE acronym = 'MXN';
UPDATE currency SET name = 'Dólar Estadounidense ($)', country_name = 'Estados Unidos', country_code = 'US' WHERE acronym = 'USD';
UPDATE currency SET name = 'Bitcoin (₿)', country_name = NULL, country_code = NULL WHERE acronym = 'BTC';

CREATE UNIQUE INDEX IF NOT EXISTS idx_currency_acronym_unique ON currency(acronym);

INSERT OR IGNORE INTO currency (id, acronym, name, country_name, country_code) VALUES
  (lower(hex(randomblob(16))), 'CAD', 'Dólar Canadiense (C$)', 'Canadá', 'CA'),
  (lower(hex(randomblob(16))), 'HNL', 'Lempira Hondureño (L)', 'Honduras', 'HN'),
  (lower(hex(randomblob(16))), 'GTQ', 'Quetzal Guatemalteco (Q)', 'Guatemala', 'GT'),
  (lower(hex(randomblob(16))), 'CRC', 'Colón Costarricense (₡)', 'Costa Rica', 'CR'),
  (lower(hex(randomblob(16))), 'NIO', 'Córdoba Nicaragüense (C$)', 'Nicaragua', 'NI'),
  (lower(hex(randomblob(16))), 'PAB', 'Balboa Panameño (B/.)', 'Panamá', 'PA'),
  (lower(hex(randomblob(16))), 'JMD', 'Dólar Jamaicano (J$)', 'Jamaica', 'JM'),
  (lower(hex(randomblob(16))), 'DOP', 'Peso Dominicano (RD$)', 'República Dominicana', 'DO'),
  (lower(hex(randomblob(16))), 'CUP', 'Peso Cubano (₱)', 'Cuba', 'CU'),
  (lower(hex(randomblob(16))), 'COP', 'Peso Colombiano ($)', 'Colombia', 'CO'),
  (lower(hex(randomblob(16))), 'VES', 'Bolívar Venezolano (Bs.)', 'Venezuela', 'VE'),
  (lower(hex(randomblob(16))), 'ARS', 'Peso Argentino ($)', 'Argentina', 'AR'),
  (lower(hex(randomblob(16))), 'BRL', 'Real Brasileño (R$)', 'Brasil', 'BR'),
  (lower(hex(randomblob(16))), 'CLP', 'Peso Chileno ($)', 'Chile', 'CL'),
  (lower(hex(randomblob(16))), 'PEN', 'Sol Peruano (S/.)', 'Perú', 'PE'),
  (lower(hex(randomblob(16))), 'BOB', 'Boliviano (Bs.)', 'Bolivia', 'BO'),
  (lower(hex(randomblob(16))), 'UYU', 'Peso Uruguayo ($U)', 'Uruguay', 'UY'),
  (lower(hex(randomblob(16))), 'PYG', 'Guaraní Paraguayo (₲)', 'Paraguay', 'PY'),
  (lower(hex(randomblob(16))), 'EUR', 'Euro (€)', 'Eurozona', 'EU'),
  (lower(hex(randomblob(16))), 'GBP', 'Libra Esterlina (£)', 'Reino Unido', 'GB'),
  (lower(hex(randomblob(16))), 'CHF', 'Franco Suizo (Fr.)', 'Suiza', 'CH'),
  (lower(hex(randomblob(16))), 'SEK', 'Corona Sueca (kr)', 'Suecia', 'SE'),
  (lower(hex(randomblob(16))), 'NOK', 'Corona Noruega (kr)', 'Noruega', 'NO'),
  (lower(hex(randomblob(16))), 'DKK', 'Corona Danesa (kr.)', 'Dinamarca', 'DK'),
  (lower(hex(randomblob(16))), 'ISK', 'Corona Islandesa (kr)', 'Islandia', 'IS'),
  (lower(hex(randomblob(16))), 'PLN', 'Esloti Polaco (zł)', 'Polonia', 'PL'),
  (lower(hex(randomblob(16))), 'CZK', 'Corona Checa (Kč)', 'República Checa', 'CZ'),
  (lower(hex(randomblob(16))), 'HUF', 'Florín Húngaro (Ft)', 'Hungría', 'HU'),
  (lower(hex(randomblob(16))), 'RON', 'Leu Rumano (lei)', 'Rumania', 'RO'),
  (lower(hex(randomblob(16))), 'BGN', 'Lev Búlgaro (лв)', 'Bulgaria', 'BG'),
  (lower(hex(randomblob(16))), 'HRK', 'Kuna Croata (kn)', 'Croacia', 'HR'),
  (lower(hex(randomblob(16))), 'RUB', 'Rublo Ruso (₽)', 'Rusia', 'RU'),
  (lower(hex(randomblob(16))), 'UAH', 'Grivnia Ucraniana (₴)', 'Ucrania', 'UA'),
  (lower(hex(randomblob(16))), 'TRY', 'Lira Turca (₺)', 'Turquía', 'TR'),
  (lower(hex(randomblob(16))), 'AED', 'Dírham de los EAU (د.إ)', 'Emiratos Árabes Unidos', 'AE'),
  (lower(hex(randomblob(16))), 'SAR', 'Rial Saudí (﷼)', 'Arabia Saudita', 'SA'),
  (lower(hex(randomblob(16))), 'QAR', 'Rial Qatarí (﷼)', 'Qatar', 'QA'),
  (lower(hex(randomblob(16))), 'KWD', 'Dinar Kuwaití (د.ك)', 'Kuwait', 'KW'),
  (lower(hex(randomblob(16))), 'BHD', 'Dinar Bahreiní (.د.ب)', 'Baréin', 'BH'),
  (lower(hex(randomblob(16))), 'OMR', 'Rial de Omán (ر.ع.)', 'Omán', 'OM'),
  (lower(hex(randomblob(16))), 'JOD', 'Dinar Jordano (د.ا)', 'Jordania', 'JO'),
  (lower(hex(randomblob(16))), 'ILS', 'Shequel Israelí (₪)', 'Israel', 'IL'),
  (lower(hex(randomblob(16))), 'EGP', 'Libra Egipcia (£)', 'Egipto', 'EG'),
  (lower(hex(randomblob(16))), 'IRR', 'Rial Iraní (﷼)', 'Irán', 'IR'),
  (lower(hex(randomblob(16))), 'IQD', 'Dinar Iraquí (ع.د)', 'Irak', 'IQ'),
  (lower(hex(randomblob(16))), 'LBP', 'Libra Libanesa (£)', 'Líbano', 'LB'),
  (lower(hex(randomblob(16))), 'INR', 'Rupia India (₹)', 'India', 'IN'),
  (lower(hex(randomblob(16))), 'PKR', 'Rupia Paquistaní (₨)', 'Pakistán', 'PK'),
  (lower(hex(randomblob(16))), 'BDT', 'Taka Bangladesí (৳)', 'Bangladés', 'BD'),
  (lower(hex(randomblob(16))), 'LKR', 'Rupia de Sri Lanka (Rs)', 'Sri Lanka', 'LK'),
  (lower(hex(randomblob(16))), 'NPR', 'Rupia Nepalí (₨)', 'Nepal', 'NP'),
  (lower(hex(randomblob(16))), 'MVR', 'Rupia de Maldivas (Rf)', 'Maldivas', 'MV'),
  (lower(hex(randomblob(16))), 'BTN', 'Ngultrum de Bután (Nu.)', 'Bután', 'BT'),
  (lower(hex(randomblob(16))), 'CNY', 'Yuan Chino (¥)', 'China', 'CN'),
  (lower(hex(randomblob(16))), 'JPY', 'Yen Japonés (¥)', 'Japón', 'JP'),
  (lower(hex(randomblob(16))), 'KRW', 'Won Surcoreano (₩)', 'Corea del Sur', 'KR'),
  (lower(hex(randomblob(16))), 'TWD', 'Dólar Taiwanés (NT$)', 'Taiwán', 'TW'),
  (lower(hex(randomblob(16))), 'HKD', 'Dólar de Hong Kong (HK$)', 'Hong Kong', 'HK'),
  (lower(hex(randomblob(16))), 'SGD', 'Dólar de Singapur (S$)', 'Singapur', 'SG'),
  (lower(hex(randomblob(16))), 'MYR', 'Ringgit Malasio (RM)', 'Malasia', 'MY'),
  (lower(hex(randomblob(16))), 'THB', 'Baht Tailandés (฿)', 'Tailandia', 'TH'),
  (lower(hex(randomblob(16))), 'VND', 'Dong Vietnamita (₫)', 'Vietnam', 'VN'),
  (lower(hex(randomblob(16))), 'IDR', 'Rupia Indonesia (Rp)', 'Indonesia', 'ID'),
  (lower(hex(randomblob(16))), 'PHP', 'Peso Filipino (₱)', 'Filipinas', 'PH'),
  (lower(hex(randomblob(16))), 'AUD', 'Dólar Australiano (A$)', 'Australia', 'AU'),
  (lower(hex(randomblob(16))), 'NZD', 'Dólar Neozelandés (NZ$)', 'Nueva Zelanda', 'NZ'),
  (lower(hex(randomblob(16))), 'FJD', 'Dólar Fiyiano (FJ$)', 'Fiyi', 'FJ'),
  (lower(hex(randomblob(16))), 'ZAR', 'Rand Sudafricano (R)', 'Sudáfrica', 'ZA'),
  (lower(hex(randomblob(16))), 'NGN', 'Naira Nigeriana (₦)', 'Nigeria', 'NG'),
  (lower(hex(randomblob(16))), 'GHS', 'Cedi Ghanés (₵)', 'Ghana', 'GH'),
  (lower(hex(randomblob(16))), 'KES', 'Chelín Keniata (KSh)', 'Kenia', 'KE'),
  (lower(hex(randomblob(16))), 'ETB', 'Birr Etíope (Br)', 'Etiopía', 'ET'),
  (lower(hex(randomblob(16))), 'MAD', 'Dirham Marroquí (د.م.)', 'Marruecos', 'MA'),
  (lower(hex(randomblob(16))), 'TND', 'Dinar Tunecino (د.ت)', 'Túnez', 'TN'),
  (lower(hex(randomblob(16))), 'DZD', 'Dinar Argelino (د.ج)', 'Argelia', 'DZ'),
  (lower(hex(randomblob(16))), 'UGX', 'Chelín Ugandés (USh)', 'Uganda', 'UG'),
  (lower(hex(randomblob(16))), 'RWF', 'Franco Ruandés (FRw)', 'Ruanda', 'RW'),
  (lower(hex(randomblob(16))), 'TZS', 'Chelín Tanzano (TSh)', 'Tanzania', 'TZ'),
  (lower(hex(randomblob(16))), 'MUR', 'Rupia Mauriciana (₨)', 'Mauricio', 'MU');

