export const CURRENCIES_EN = [
  { code: "USD", name: "United States Dollar ($)" },
  { code: "CAD", name: "Canadian Dollar (C$)" },
  { code: "MXN", name: "Mexican Peso ($)" },
  { code: "HNL", name: "Honduran Lempira (L)" },
  { code: "GTQ", name: "Guatemalan Quetzal (Q)" },
  { code: "CRC", name: "Costa Rican Colón (₡)" },
  { code: "NIO", name: "Nicaraguan Córdoba (C$)" },
  { code: "PAB", name: "Panamanian Balboa (B/.)" },
  { code: "JMD", name: "Jamaican Dollar (J$)" },
  { code: "DOP", name: "Dominican Peso (RD$)" },
  { code: "CUP", name: "Cuban Peso (₱)" },
  { code: "COP", name: "Colombian Peso ($)" },
  { code: "VES", name: "Venezuelan Bolívar (Bs.)" },
  { code: "ARS", name: "Argentine Peso ($)" },
  { code: "BRL", name: "Brazilian Real (R$)" },
  { code: "CLP", name: "Chilean Peso ($)" },
  { code: "PEN", name: "Peruvian Sol (S/.)" },
  { code: "BOB", name: "Bolivian Boliviano (Bs.)" },
  { code: "UYU", name: "Uruguayan Peso ($U)" },
  { code: "PYG", name: "Paraguayan Guaraní (₲)" },
  { code: "USD", name: "Ecuadorian Dollar (US$)" },
  { code: "EUR", name: "Euro (€)" },
  { code: "GBP", name: "British Pound Sterling (£)" },
  { code: "CHF", name: "Swiss Franc (Fr.)" },
  { code: "SEK", name: "Swedish Krona (kr)" },
  { code: "NOK", name: "Norwegian Krone (kr)" },
  { code: "DKK", name: "Danish Krone (kr.)" },
  { code: "ISK", name: "Icelandic Krona (kr)" },
  { code: "PLN", name: "Polish Zloty (zł)" },
  { code: "CZK", name: "Czech Koruna (Kč)" },
  { code: "HUF", name: "Hungarian Forint (Ft)" },
  { code: "RON", name: "Romanian Leu (lei)" },
  { code: "BGN", name: "Bulgarian Lev (лв)" },
  { code: "HRK", name: "Croatian Kuna (kn)" },
  { code: "RUB", name: "Russian Ruble (₽)" },
  { code: "UAH", name: "Ukrainian Hryvnia (₴)" },
  { code: "TRY", name: "Turkish Lira (₺)" },
  { code: "AED", name: "UAE Dirham (د.إ)" },
  { code: "SAR", name: "Saudi Riyal (﷼)" },
  { code: "QAR", name: "Qatari Riyal (﷼)" },
  { code: "KWD", name: "Kuwaiti Dinar (د.ك)" },
  { code: "BHD", name: "Bahraini Dinar (.د.ب)" },
  { code: "OMR", name: "Omani Rial (ر.ع.)" },
  { code: "JOD", name: "Jordanian Dinar (د.ا)" },
  { code: "ILS", name: "Israeli Shekel (₪)" },
  { code: "EGP", name: "Egyptian Pound (£)" },
  { code: "IRR", name: "Iranian Rial (﷼)" },
  { code: "IQD", name: "Iraqi Dinar (ع.د)" },
  { code: "LBP", name: "Lebanese Pound (£)" },
  { code: "INR", name: "Indian Rupee (₹)" },
  { code: "PKR", name: "Pakistani Rupee (₨)" },
  { code: "BDT", name: "Bangladeshi Taka (৳)" },
  { code: "LKR", name: "Sri Lankan Rupee (Rs)" },
  { code: "NPR", name: "Nepalese Rupee (₨)" },
  { code: "MVR", name: "Maldivian Rufiyaa (Rf)" },
  { code: "BTN", name: "Bhutanese Ngultrum (Nu.)" },
  { code: "CNY", name: "Chinese Yuan (¥)" },
  { code: "JPY", name: "Japanese Yen (¥)" },
  { code: "KRW", name: "South Korean Won (₩)" },
  { code: "TWD", name: "New Taiwan Dollar (NT$)" },
  { code: "HKD", name: "Hong Kong Dollar (HK$)" },
  { code: "SGD", name: "Singapore Dollar (S$)" },
  { code: "MYR", name: "Malaysian Ringgit (RM)" },
  { code: "THB", name: "Thai Baht (฿)" },
  { code: "VND", name: "Vietnamese Dong (₫)" },
  { code: "IDR", name: "Indonesian Rupiah (Rp)" },
  { code: "PHP", name: "Philippine Peso (₱)" },
  { code: "AUD", name: "Australian Dollar (A$)" },
  { code: "NZD", name: "New Zealand Dollar (NZ$)" },
  { code: "FJD", name: "Fijian Dollar (FJ$)" },
  { code: "ZAR", name: "South African Rand (R)" },
  { code: "NGN", name: "Nigerian Naira (₦)" },
  { code: "GHS", name: "Ghanaian Cedi (₵)" },
  { code: "KES", name: "Kenyan Shilling (KSh)" },
  { code: "ETC", name: "Ethiopian Birr (Br)" },
  { code: "MAD", name: "Moroccan Dirham (د.م.)" },
  { code: "TND", name: "Tunisian Dinar (د.ت)" },
  { code: "DZD", name: "Algerian Dinar (د.ج)" },
  { code: "UGX", name: "Ugandan Shilling (USh)" },
  { code: "RWF", name: "Rwandan Franc (FRw)" },
  { code: "TZS", name: "Tanzanian Shilling (TSh)" },
  { code: "MUR", name: "Mauritian Rupee (₨)" },
];
